version: '3'
services:
  sender:
    build: ./sender/
    environment: 
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHANNELNAME=${TELEGRAM_CHANNELNAME}
      - INSTAGRAM_TAGNAME=${INSTAGRAM_TAGNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./sender/code/:/app/code/
    restart: always
  
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - 6379:6379
    labels:
      kompose.service.type: nodeport
    volumes:
      - './redis/redis_data/:/bitnami/redis/data'
    restart: always